Repository RAF-SI-2022/Banka-2-Backend, pull requests merged in 2023-05, with the labels that each got.

#179 testovi fixovani
  src/main/java/com/raf/si/Banka2Backend/controllers/ForexController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/TransactionController.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/ExchangeNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/java/com/raf/si/Banka2Backend/services/TransactionService.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/StockSellWorker.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/exchangesFailure/ExchangeFailuresIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/forex/ForexIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/forexFailure/ForexFailureIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/stocks/StocksIntegrationSteps.java
Labels: size/M

#180 change in controller responses (promenjeno na sprski)
  src/main/java/com/raf/si/Banka2Backend/controllers/AuthenticationController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/BalanceController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/CurrencyController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/ForexController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/FutureController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/OptionController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/OrderController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/StockController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/services/FutureService.java
  src/main/java/com/raf/si/Banka2Backend/services/OrderService.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/java/com/raf/si/Banka2Backend/services/UserService.java
Labels: size/L

#182 add order and transactions in future buying and selling
  src/main/java/com/raf/si/Banka2Backend/controllers/FutureController.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Balance.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Future.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Transaction.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/User.java
  src/main/java/com/raf/si/Banka2Backend/requests/FutureRequestBuySell.java
  src/main/java/com/raf/si/Banka2Backend/services/BalanceService.java
  src/main/java/com/raf/si/Banka2Backend/services/FutureService.java
  src/main/java/com/raf/si/Banka2Backend/services/TransactionService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/TransactionServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureBuyWorker.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureSellWorker.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/StockSellWorker.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/forexFailure/ForexFailureIntegrationSteps.java
Labels: size/XL

#183 Popravljeni bugovi za stock
  src/main/java/com/raf/si/Banka2Backend/controllers/BalanceController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/CurrencyController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/ForexController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/FutureController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/TransactionController.java
  src/main/java/com/raf/si/Banka2Backend/dto/OptionBuyDto.java
  src/main/java/com/raf/si/Banka2Backend/dto/SellStockUsingOptionDto.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/NotEnoughReservedMoneyException.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/OrderNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/TooLateToBuyOptionException.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/TransactionNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Balance.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Transaction.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/User.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/ForexOrder.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/FutureOrder.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/OptionOrder.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/StockOrder.java
  src/main/java/com/raf/si/Banka2Backend/services/FutureService.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/java/com/raf/si/Banka2Backend/services/TransactionService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/TransactionServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureBuyWorker.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureSellWorker.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/StockBuyWorker.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/forex/ForexIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/forexFailure/ForexFailureIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/usersFailures/UserFailuresSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/usersFailures/UsersFailureIntegrationTestConfig.java
Labels: size/XL

#188 Dodati unit testovi
  pom.xml
  src/main/java/com/raf/si/Banka2Backend/services/ForexService.java
  src/main/java/com/raf/si/Banka2Backend/services/OptionService.java
  src/test/java/com/raf/si/Banka2Backend/services/ExchangeServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/ForexServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/MailingServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/OptionServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/OrderServiceTest.java
  src/test/resources/features/options-integration/options.feature
  src/test/resources/features/options-integration/optionsFailures.feature
Labels: size/XXL

#190 Docker/Make updates for frontend+backend running & more
  .gitattributes
  .prow/main.yaml
  Makefile
  docker-compose.yml
  docker/backend.Dockerfile
  docker/prod.Dockerfile
  docker/test.Dockerfile
  make.cmd
  pom.xml
  src/main/resources/application-container.properties
  src/main/resources/application-dev.properties
  src/main/resources/application-local.properties
  src/main/resources/application-prod.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/main/resources/csvs/future_data.csv
  src/main/resources/db/migration/V1_0__Initial_migration_users_table.sql
  src/main/resources/db/migration/V1_1__Permission_support_added.sql
  src/main/resources/db/migration/V1_3__Password_reset.sql
  src/main/resources/db/migration/V1_4__Exchange.sql
  src/main/resources/db/migration/V2_0__Initial_migration_currencies_table.sql
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/forex/ForexIntegrationSteps.java
  src/test/resources/features/forex-integration/forexFailure.feature
Labels: size/XL

#191 Kostur za option ordere i tranzakcije testovi za order kontroler
  src/main/java/com/raf/si/Banka2Backend/controllers/OrderController.java
  src/main/java/com/raf/si/Banka2Backend/services/OptionService.java
  src/main/java/com/raf/si/Banka2Backend/services/OrderService.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/resources/db/migration/V3_2__update_order_type.sql
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/order/OrderIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/order/OrderIntegrationTest.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/order/OrderIntegrationTestConfig.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/orderFailures/OrderFailuresIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/orderFailures/OrderFailuresIntegrationTest.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/orderFailures/OrderIntegrationFailuresTestConfig.java
  src/test/java/com/raf/si/Banka2Backend/services/OptionServiceTest.java
  src/test/resources/features/order-integration/order.feature
  src/test/resources/features/order-integration/orderFailures.feature
Labels: size/XL

#192 StockService cleanup and unit tests
  .mvn/wrapper/maven-wrapper.jar
  docker/test-devenv.ubuntu.aarch64.Dockerfile
  docker/test-devenv.ubuntu.x64.Dockerfile
  docker/test.Dockerfile
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/test/java/com/raf/si/Banka2Backend/services/StockServiceTest.java
  src/test/resources/features/stock-integration/stocksFailures.feature
Labels: size/L

#197 Maven wrapper, Prow fix
  .gitattributes
  .mvn/wrapper/maven-wrapper.jar
  .prow/main.yaml
  Makefile
  README.md
  docker/test.Dockerfile
  make.cmd
  src/main/java/com/raf/si/Banka2Backend/controllers/OrderController.java
  src/main/java/com/raf/si/Banka2Backend/services/OptionService.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/StockBuyWorker.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/order/OrderIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/order/OrderIntegrationTest.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/order/OrderIntegrationTestConfig.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/orderFailures/OrderFailuresIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/orderFailures/OrderFailuresIntegrationTest.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/orderFailures/OrderIntegrationFailuresTestConfig.java
  src/test/java/com/raf/si/Banka2Backend/services/OptionServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/StockServiceTest.java
Labels: size/XL

#198 Sprint 4 (Checkpoint: popravka KT za prvu kolokvijumsku nedelju)
  .gitattributes
  .mvn/wrapper/maven-wrapper.jar
  .prow/main.yaml
  Makefile
  README.md
  docker/test.Dockerfile
  make.cmd
  src/main/java/com/raf/si/Banka2Backend/controllers/OrderController.java
  src/main/java/com/raf/si/Banka2Backend/services/OptionService.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/StockBuyWorker.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/order/OrderIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/order/OrderIntegrationTest.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/order/OrderIntegrationTestConfig.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/orderFailures/OrderFailuresIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/orderFailures/OrderFailuresIntegrationTest.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/orderFailures/OrderIntegrationFailuresTestConfig.java
  src/test/java/com/raf/si/Banka2Backend/services/OptionServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/StockServiceTest.java
Labels: size/XL

#213 Sprint 5 - patchovani testovi, izbacen --local i dodat IntelliJ kostur za projekat; Redis servis
  .build/out/rs/edu/raf/si/bank2/ArgParser.class
  .build/out/rs/edu/raf/si/bank2/Main.class
  .build/src/rs/edu/raf/si/bank2/ArgParser.java
  .build/src/rs/edu/raf/si/bank2/Main.java
  .github/workflows/pull-request-test.yml
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/.build.iml
  .idea/modules/main.iml
  .idea/runConfigurations/Main__DEV_.xml
  .idea/runConfigurations/Main__TEST_.xml
  .idea/runConfigurations/Main__format_.xml
  .idea/runConfigurations/run_dev__Docker_.xml
  .idea/runConfigurations/run_init.xml
  .idea/runConfigurations/run_stack.xml
  .idea/runConfigurations/run_test__Docker_.xml
  .idea/vcs.xml
  bank2.iml
  docker-compose.yml
  main/pom.xml
  main/src/main/java/rs/edu/raf/si/bank2/main/bootstrap/BootstrapData.java
  main/src/main/java/rs/edu/raf/si/bank2/main/bootstrap/readers/CurrencyReader.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/ExchangeController.java
  main/src/main/resources/application-container.properties
  main/src/main/resources/application-dev.properties
  main/src/main/resources/application-local.properties
  main/src/main/resources/application-prod.properties
  main/src/main/resources/application-test.properties
  main/src/main/resources/application.properties
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/exchanges/ExchangesIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/future/FutureIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/futureFailure/FutureFailureIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/option/OptionIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/optionFailure/OptionIntegrationFailureSteps.java
  pom.xml
  run
Labels: size/XXL

#214 FutureFailureIntegrationSteps minor patch
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/futureFailure/FutureFailureIntegrationSteps.java
Labels: size/S

#216 dodati testovi do 80%
  .idea/Banka-2-Backend.iml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/jpa-buddy.xml
  .idea/misc.xml
  .idea/modules.xml
  bank2.iml
  main/pom.xml
  main/src/main/java/rs/edu/raf/si/bank2/main/bootstrap/BootstrapData.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/ForexController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/StockService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/workerThreads/StockBuyWorker.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/balance/BalanceIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/balance/BalanceIntegrationTest.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/balance/BalanceIntegrationTestConfig.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/balanceFailure/BalanceFailureIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/balanceFailure/BalanceFailureIntegrationTest.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/balanceFailure/BalanceFailureIntegrationTestConfig.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/forex/ForexIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/option/OptionIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/stocks/StocksIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/users/UsersIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/usersFailures/UserFailuresSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/services/StockServiceTest.java
  main/src/test/resources/features/balance-integration/balance.feature
  main/src/test/resources/features/balance-integration/balanceFailure.feature
  main/src/test/resources/features/options-integration/options.feature
  main/src/test/resources/features/order-integration/order.feature
  main/src/test/resources/features/stock-integration/stocks.feature
  main/src/test/resources/features/user-integration/users.feature
  main/src/test/resources/features/user-integration/usersFailures.feature
Labels: size/XL

#218 redis implementiran
  .idea/CoverUsage.xml
  .idea/dataSources.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  Banka2Backend.iml
  main/src/main/java/rs/edu/raf/si/bank2/main/configuration/RedisTestConfiguration.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/ExchangeController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/ExchangeService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/StockService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/interfaces/ExchangeServiceInterface.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/exchanges/ExchangesIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/exchangesFailure/ExchangeFailuresIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/services/ExchangeServiceTest.java
  main/src/test/resources/features/exchange-integration/exchange.feature
Labels: size/L

#226 rad na komunikacija servisa
  main/src/main/java/rs/edu/raf/si/bank2/main/bootstrap/BootstrapData.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/UserController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/CommunicationService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/interfaces/CommunicationInterface.java
  main/src/main/resources/application.properties
  users/src/main/java/rs/edu/raf/si/bank2/users/bootstrap/BootstrapData.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/BalanceController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/CurrencyController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/ExchangeController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/ForexController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/FutureController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/OptionController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/OrderController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/StockController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/TransactionController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/UserController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/UserServiceCommunicationController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/BalanceRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/CurrencyRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/ExchangeRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/ForexRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/FutureRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/InflationRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/OptionRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/OrderRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/StockHistoryRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/StockRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/TransactionRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/UserOptionRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/repositories/mariadb/UserStocksRepository.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/BalanceService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/CurrencyService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/ExchangeService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/ForexService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/FutureService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/InflationService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/OptionService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/OrderService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/StockService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/TransactionService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/UserStockService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/BalanceServiceInterface.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/CurrencyServiceInterface.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/ExchangeServiceInterface.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/ForexServiceInterface.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/FutureServiceInterface.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/InflationServiceInterface.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/OptionServiceInterface.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/OrderServiceInterface.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/TransactionServiceInterface.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/UserStockServiceInterface.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/workerThreads/FutureBuyWorker.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/workerThreads/FutureSellWorker.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/workerThreads/StockBuyWorker.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/workerThreads/StockSellWorker.java
Labels: size/XXL

#232 popravljeni testovi koji padaju
  main/src/main/java/rs/edu/raf/si/bank2/main/bootstrap/BootstrapData.java
  main/src/main/java/rs/edu/raf/si/bank2/main/models/mariadb/Permission.java
  main/src/main/java/rs/edu/raf/si/bank2/main/models/mariadb/User.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/BalanceService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/FutureService.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/futureFailure/FutureFailureIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/services/FutureServiceTest.java
  main/src/test/resources/features/future-integration/futureFailure.feature
  main/src/test/resources/features/order-integration/order.feature
  main/src/test/resources/features/stock-integration/stocks.feature
Labels: size/L
