Repository RAF-SI-2022/Banka-2-Backend, pull requests merged in 2023-04, with the labels that each got.

#101 Commented out "report" job temporarily until fixed
  .github/workflows/pull-request-test.yml
Labels: size/S, approved

#103 povezani exchange i currency, flyway i csv updateovan, i dodati integracioni testovi za exchange
  Makefile
  docker/test-devenv.sh
  git/hooks/pre-push
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/ForexController.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/ExchangeNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Exchange.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Forex.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Future.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/User.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/CurrencyRepository.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/ForexRepository.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/FutureRepository.java
  src/main/java/com/raf/si/Banka2Backend/requests/BuyForexRequest.java
  src/main/java/com/raf/si/Banka2Backend/services/ExchangeService.java
  src/main/java/com/raf/si/Banka2Backend/services/ForexService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/ForexServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/FutureServiceInterface.java
  src/main/resources/csvs/exchange.csv
  src/main/resources/db/migration/V2_2__Change_exchange_to_reference_table_currencies.sql
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/exchanges/ExchangesIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/exchanges/ExchangesIntegrationTest.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/exchanges/ExchangesIntegrationTestConfig.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/exchangesFailure/ExchangeFailuresIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/exchangesFailure/ExchangeFailuresIntegrationTest.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/exchangesFailure/ExchangeFailuresIntegrationTestConfig.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/future/FutureIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/services/ExchangeServiceTest.java
  src/test/resources/features/exchange-integration/exchange.feature
  src/test/resources/features/exchange-integration/exchangeFailures.feature
Labels: size/XXL

#108 Balance model, forex buy-sell
  Makefile
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/BalanceController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/CurrencyController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/ForexController.java
  src/main/java/com/raf/si/Banka2Backend/dto/BalanceDto.java
  src/main/java/com/raf/si/Banka2Backend/dto/BuySellForexDto.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/BalanceNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/NotEnoughMoneyException.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Balance.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/User.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/BalanceRepository.java
  src/main/java/com/raf/si/Banka2Backend/services/BalanceService.java
  src/main/java/com/raf/si/Banka2Backend/services/CurrencyService.java
  src/main/java/com/raf/si/Banka2Backend/services/UserService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/BalanceServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/CurrencyServiceInterface.java
  src/main/resources/db/migration/V2_4__Initial_migration_balances_table.sql
Labels: size/XXL

#109 fixes on futures
  src/main/java/com/raf/si/Banka2Backend/controllers/FutureController.java
  src/main/java/com/raf/si/Banka2Backend/services/FutureService.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureBuyWorker.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureSellWorker.java
Labels: size/M

#115 Stock feature
  pom.xml
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/configuration/SpringSecurityConfig.java
  src/main/java/com/raf/si/Banka2Backend/controllers/ForexController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/FutureController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/OrderController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/StockController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/StockNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Future.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Order.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Stock.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/StockHistory.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/StockHistoryType.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/User.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/BalanceRepository.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/OrderRepository.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/StockHistoryRepository.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/StockRepository.java
  src/main/java/com/raf/si/Banka2Backend/services/BalanceService.java
  src/main/java/com/raf/si/Banka2Backend/services/CurrencyService.java
  src/main/java/com/raf/si/Banka2Backend/services/FutureService.java
  src/main/java/com/raf/si/Banka2Backend/services/OrderService.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/BalanceServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/FutureServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/OrderServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureBuyWorker.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureSellWorker.java
  src/main/resources/db/migration/V2_2_1__Change_exchange_to_reference_table_currencies.sql
  src/main/resources/db/migration/V2_3_1__Initial_migration_forex_table.sql
  src/main/resources/db/migration/V2_6__Stock_table_script.sql
  src/main/resources/db/migration/V2_7__Stock_history_table_script.sql
  src/main/resources/exchange.csv
  src/main/resources/stock_history.csv
  src/main/resources/stocks.csv
Labels: size/XXL

#114 Add futures routes and fixes
  src/main/java/com/raf/si/Banka2Backend/controllers/FutureController.java
  src/main/java/com/raf/si/Banka2Backend/services/FutureService.java
  src/main/java/com/raf/si/Banka2Backend/services/UserService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/FutureServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureBuyWorker.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureSellWorker.java
  src/main/resources/application-local.properties
Labels: size/L

#122 Stock feature - Added connections to external API
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/StockController.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/StockHistoryRepository.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/resources/db/migration/V2_6__Stock_table_script.sql
  src/main/resources/db/migration/V2_7__Stock_history_table_script.sql
Labels: size/XXL

#123 Stock feature changes
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/StockController.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/ExternalAPILimitReachedException.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/StockHistoryRepository.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/resources/db/migration/V2_8__user_stocks_table_script.sql
Labels: size/M

#124 User stocks route
  src/main/java/com/raf/si/Banka2Backend/controllers/StockController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/User.java
  src/main/java/com/raf/si/Banka2Backend/requests/UpdateUserRequest.java
  src/main/java/com/raf/si/Banka2Backend/services/ForexService.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
Labels: size/S

#156 Removed deleted exception usages
  src/main/java/com/raf/si/Banka2Backend/controllers/OptionController.java
  src/main/java/com/raf/si/Banka2Backend/services/OptionService.java
Labels: size/S

#157 Continued work on OptionService
  src/main/java/com/raf/si/Banka2Backend/controllers/OptionController.java
  src/main/java/com/raf/si/Banka2Backend/dto/OptionSellDto.java
  src/main/java/com/raf/si/Banka2Backend/dto/SellStockUsingOptionDto.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/NotEnoughOptionsAvailableException.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/OptionNotInTheMoneyException.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/TooLateToBuyOptionException.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/UserOption.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/UserStock.java
  src/main/java/com/raf/si/Banka2Backend/services/OptionService.java
  src/main/resources/db/migration/V2_10__user_options_table.sql
Labels: size/L

#158 Option date scraper, limit and fixes
  pom.xml
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/OptionController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/User.java
  src/main/java/com/raf/si/Banka2Backend/responses/RegisterResponse.java
  src/main/java/com/raf/si/Banka2Backend/services/FutureService.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/FutureBuyWorker.java
  src/main/java/com/raf/si/Banka2Backend/utils/OptionDateScraper.java
  src/main/resources/db/migration/V1_0__Initial_migration_users_table.sql
Labels: size/L

#159 impl Transaction model, update Balance service, update Order model
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/NotEnoughReservedMoneyException.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/TransactionNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Balance.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/BalanceType.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Order.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Transaction.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/TransactionStatus.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/Order.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/OrderStatus.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/OrderTradeType.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/OrderType.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/OrderRepository.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/TransactionRepository.java
  src/main/java/com/raf/si/Banka2Backend/services/BalanceService.java
  src/main/java/com/raf/si/Banka2Backend/services/OrderService.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/java/com/raf/si/Banka2Backend/services/TransactionService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/BalanceServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/OrderServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/TransactionServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/StockBuyWorker.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/StockSellWorker.java
  src/main/resources/db/migration/V3_0__update_balances_&_orders_add_transactions_table.sql
Labels: size/L

#162 Change on options model
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Option.java
  src/main/java/com/raf/si/Banka2Backend/services/OptionService.java
  src/main/resources/db/migration/V2_9__options_table.sql
Labels: size/M

#163 Orders and transactions
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/configuration/SpringSecurityConfig.java
  src/main/java/com/raf/si/Banka2Backend/controllers/BalanceController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/ForexController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/OrderController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/StockController.java
  src/main/java/com/raf/si/Banka2Backend/dto/BuySellForexDto.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/OrderNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/ForexOrder.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/FutureOrder.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/OptionOrder.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/Order.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/OrderType.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/orders/StockOrder.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/OrderRepository.java
  src/main/java/com/raf/si/Banka2Backend/requests/StockRequest.java
  src/main/java/com/raf/si/Banka2Backend/services/BalanceService.java
  src/main/java/com/raf/si/Banka2Backend/services/OrderService.java
  src/main/java/com/raf/si/Banka2Backend/services/StockService.java
  src/main/java/com/raf/si/Banka2Backend/services/TransactionService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/BalanceServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/OrderServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/TransactionServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/StockBuyWorker.java
  src/main/java/com/raf/si/Banka2Backend/services/workerThreads/StockSellWorker.java
  src/main/resources/db/migration/V3_1__update_orders.sql
Labels: size/XL
