Repository RAF-SI-2022/Banka-2-Backend, pull requests merged in 2023-06, with the labels that each got.

#236 mali fix za velike ljude
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/CompanyController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/dto/CommunicationDto.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/dto/ContactsBankAccountsDto.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/dto/CreateCompanyDto.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/dto/EditCompanyDto.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/models/mongodb/Company.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/repositories/mongodb/CompanyBankAccountRepository.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/repositories/mongodb/CompanyRepository.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/repositories/mongodb/ContactPersonRepository.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/services/CompanyService.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/services/UserCommunicationService.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/services/interfaces/UserCommunicationInterface.java
  otc/src/main/resources/application.properties
Labels: size/L

#239 Fix bug with daily limit when buying stock
  main/src/main/java/rs/edu/raf/si/bank2/main/services/StockService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/workerThreads/OptionsRetrieverFromApiWorker.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/workerThreads/StockBuyWorker.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/workerThreads/StocksRetrieverFromApiWorker.java
Labels: size/S

#240 Reviewed additional tests from Testovi #234 pull request from @BrnabicMateja
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/forexFailure/ForexFailureIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/future/FutureIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/futureFailure/FutureFailureIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/orderFailures/OrderFailuresIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/stockFailure/StockFailureIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/stocks/StocksIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/usersFailures/UserFailuresSteps.java
  main/src/test/resources/features/forex-integration/forexFailure.feature
  main/src/test/resources/features/future-integration/future.feature
  main/src/test/resources/features/future-integration/futureFailure.feature
  main/src/test/resources/features/order-integration/orderFailures.feature
  main/src/test/resources/features/stock-integration/stocks.feature
Labels: size/L

#242 Bez panike smiri igru, baza za pisanje unit testova postavljena
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/OrderController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/OtcApplication.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/bootstrap/BootstrapData.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/CompanyController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/MarginBalanceController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/MarginTransactionController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/dto/MarginTransactionDto.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/exceptions/BalanceByListingNotFound.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/models/mongodb/AccountType.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/models/mongodb/ListingGroup.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/models/mongodb/MarginBalance.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/models/mongodb/MarginTransaction.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/models/mongodb/OrderType.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/models/mongodb/TransactionType.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/repositories/mongodb/MarginBalanceRepository.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/repositories/mongodb/MarginTransactionRepository.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/services/MarginBalanceService.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/services/MarginCallChecker.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/services/MarginTransactionService.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/services/UserCommunicationService.java
  otc/src/main/resources/application-container.properties
  otc/src/main/resources/application.properties
  otc/src/test/java/rs/edu/raf/si/bank2/otc/services/CompanyBankAccountServiceTest.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/services/CompanyServiceTest.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/services/ContactPersonServiceTest.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/services/MarginBalanceServiceTest.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/services/MarginTransactionServiceTest.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/services/OtcServiceTest.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/services/UserCommunicationServiceTest.java
Labels: size/XL

#238 Sprint 5 otc testing
  otc/pom.xml
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/pdf/FileController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/models/mongodb/pdf/CustomMultipartFile.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/models/mongodb/pdf/LoadFile.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/services/pdf/FileService.java
Labels: size/L

#250 Fixing CICD
  .prow/prod-postsubmits.yaml
  .prow/test-presubmits.yaml
  main/src/main/resources/application-local.properties
  otc/src/main/resources/application-local.properties
Labels: size/M

#253 Popravljen Kubernetes, Helm chart, rade sve baze
  .prow/prod-postsubmits.yaml
  .prow/test-presubmits.yaml
  git/hooks/pre-commit
  git/hooks/pre-push
  kubernetes/.gitignore
  kubernetes/helm/bank-2/Chart.yaml
  kubernetes/helm/bank-2/templates/flyway-baseline.yaml
  kubernetes/helm/bank-2/templates/frontend.yaml
  kubernetes/helm/bank-2/templates/ingress.yaml
  kubernetes/helm/bank-2/templates/main.yaml
  kubernetes/helm/bank-2/templates/mariadb.yaml
  kubernetes/helm/bank-2/templates/otc.yaml
  kubernetes/helm/bank-2/templates/redis.yaml
  kubernetes/helm/bank-2/templates/users.yaml
  kubernetes/helm/bank-2/values-dev.yaml
  kubernetes/helm/bank-2/values-prod.yaml
  kubernetes/provision/mongodb/install.sh
  kubernetes/provision/mongodb/provision.sh
  kubernetes/provision/mongodb/remove.sh
  kubernetes/remove.sh
  kubernetes/scripts/build.sh
  kubernetes/scripts/deploy.sh
  kubernetes/scripts/vars.sh
  kubernetes/templates/mongo.yaml
  kubernetes/templates/relational.yaml
  kubernetes/upgrade.sh
  kubernetes/values.yaml
  run
  run.cmd
Labels: size/XL

#258 Add client to k8 vars
  kubernetes/scripts/vars.sh
Labels: size/XS

#261 Kubernetes critical server address and ports fix
  kubernetes/helm/bank-2/templates/client.yaml
  kubernetes/helm/bank-2/templates/main.yaml
  kubernetes/helm/bank-2/templates/otc.yaml
  kubernetes/helm/bank-2/templates/users.yaml
  kubernetes/helm/bank-2/values-local.yaml
Labels: size/S

#262 Client & Racun Service + Controller-i
  .idea/encodings.xml
  .idea/modules.xml
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/BalanceController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/ClientController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/BalanceDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/ClientDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/DevizniRacunDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/PoslovniRacunDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/TekuciRacunDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/Client.java
  client/src/main/java/rs/edu/raf/si/bank2/client/services/BalanceService.java
  client/src/main/java/rs/edu/raf/si/bank2/client/services/ClientService.java
Labels: size/XL

#267 dodata enumeracija racuna, za da pomognemo frontu
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/DevizniRacun.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/PoslovniRacun.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/Racun.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/TekuciRacun.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/enums/Balance.java
  client/src/main/java/rs/edu/raf/si/bank2/client/services/BalanceService.java
Labels: size/S

#274 Move infra to Banka-2-Infrastructure
  .prow/main.yaml
  .prow/otc.yaml
  .prow/prod-postsubmits.yaml
  .prow/test-presubmits.yaml
  client/src/main/resources/application-container.properties
  client/src/main/resources/application-local.properties
  client/src/main/resources/application.properties
  kubernetes/.gitignore
  kubernetes/helm/bank-2/Chart.yaml
  kubernetes/helm/bank-2/templates/client.yaml
  kubernetes/helm/bank-2/templates/flyway-baseline.yaml
  kubernetes/helm/bank-2/templates/frontend.yaml
  kubernetes/helm/bank-2/templates/ingress.yaml
  kubernetes/helm/bank-2/templates/main.yaml
  kubernetes/helm/bank-2/templates/mariadb.yaml
  kubernetes/helm/bank-2/templates/otc.yaml
  kubernetes/helm/bank-2/templates/redis.yaml
  kubernetes/helm/bank-2/templates/users.yaml
  kubernetes/helm/bank-2/values-dev.yaml
  kubernetes/helm/bank-2/values-local.yaml
  kubernetes/helm/bank-2/values-prod.yaml
  kubernetes/provision/mongodb/install.sh
  kubernetes/provision/mongodb/provision.sh
  kubernetes/provision/mongodb/remove.sh
  kubernetes/remove.sh
  kubernetes/scripts/build.sh
  kubernetes/scripts/deploy.sh
  kubernetes/scripts/vars.sh
  kubernetes/test.sh
  kubernetes/upgrade.sh
  main/src/main/java/rs/edu/raf/si/bank2/main/configuration/RedisTestConfiguration.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/ExchangeService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/ForexService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/FutureService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/OptionService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/StockService.java
  main/src/main/resources/application-container.properties
  main/src/main/resources/application-local.properties
  main/src/main/resources/application.properties
  otc/src/main/resources/application-container.properties
  otc/src/main/resources/application-local.properties
  otc/src/main/resources/application.properties
  users/src/main/java/rs/edu/raf/si/bank2/users/bootstrap/BootstrapData.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/AuthenticationController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/models/mariadb/User.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/MailingService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/interfaces/MailingServiceInterface.java
  users/src/main/resources/application-container.properties
  users/src/main/resources/application-local.properties
  users/src/main/resources/application.properties
Labels: size/XXL

#287 Fix CICD/Sonar testing, Redis fix
  .prow/client.yaml
  .prow/main.yaml
  .prow/otc.yaml
  .prow/users.yaml
  client/pom.xml
  docker-compose.yml
  docker/client.Dockerfile
  docker/main.Dockerfile
  docker/otc.Dockerfile
  docker/users.Dockerfile
  main/pom.xml
  main/src/main/java/rs/edu/raf/si/bank2/main/configuration/RedisConfiguration.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/ExchangeService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/ForexService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/FutureService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/OptionService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/StockService.java
  main/src/test/java/rs/edu/raf/si/bank2/main/services/ExchangeServiceTest.java
  otc/pom.xml
  otc/src/main/java/rs/edu/raf/si/bank2/otc/configuration/RedisConfiguration.java
  users/pom.xml
  users/src/main/java/rs/edu/raf/si/bank2/users/configuration/RedisConfiguration.java
Labels: lgtm, approved, size/XL

#289 Added dev-presubmits, fix OWNERS file
  .prow/dev-postsubmits.yaml
  CODEOWNERS
  OWNERS
Labels: lgtm, approved, size/M

#291 Fixing CICD
  .prow/client.yaml
  .prow/dev-postsubmits.yaml
  .prow/main.yaml
  .prow/otc.yaml
  .prow/users.yaml
  CODEOWNERS
  OWNERS
  client/pom.xml
  client/src/main/java/rs/edu/raf/si/bank2/client/bootstrap/BootstrapData.java
  client/src/main/java/rs/edu/raf/si/bank2/client/configuration/SpringSecurityConfig.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/ClientController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/CreditController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/PaymentController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/CreditDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/CreditRequestDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/ExchangeDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/PaymentReceiverDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/RemoveMoneyDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/Client.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/Credit.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/CreditRequest.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/PayedInterest.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/Payment.java
  client/src/main/java/rs/edu/raf/si/bank2/client/repositories/mongodb/CreditRequestRepository.java
  client/src/main/java/rs/edu/raf/si/bank2/client/repositories/mongodb/PayedInterestRepository.java
  client/src/main/java/rs/edu/raf/si/bank2/client/repositories/mongodb/PaymentRepository.java
  client/src/main/java/rs/edu/raf/si/bank2/client/services/BalanceService.java
  client/src/main/java/rs/edu/raf/si/bank2/client/services/CreditService.java
  client/src/main/java/rs/edu/raf/si/bank2/client/services/PaymentService.java
  docker-compose.yml
  docker/client.Dockerfile
  docker/main.Dockerfile
  docker/otc.Dockerfile
  docker/users.Dockerfile
  main/pom.xml
  main/src/main/java/rs/edu/raf/si/bank2/main/configuration/RedisConfiguration.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/ExchangeService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/ForexService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/FutureService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/OptionService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/StockService.java
  main/src/test/java/rs/edu/raf/si/bank2/main/services/ExchangeServiceTest.java
  otc/pom.xml
  otc/src/main/java/rs/edu/raf/si/bank2/otc/configuration/RedisConfiguration.java
  users/pom.xml
  users/src/main/java/rs/edu/raf/si/bank2/users/configuration/RedisConfiguration.java
Labels: lgtm, size/XXL, approved

#292 Sprint-6 CI/CD fixed
  .prow/client.yaml
  .prow/dev-postsubmits.yaml
  .prow/main.yaml
  .prow/otc.yaml
  .prow/users.yaml
  CODEOWNERS
  OWNERS
  client/pom.xml
  client/src/main/java/rs/edu/raf/si/bank2/client/bootstrap/BootstrapData.java
  client/src/main/java/rs/edu/raf/si/bank2/client/configuration/SpringSecurityConfig.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/ClientController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/CreditController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/PaymentController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/CreditDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/CreditRequestDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/ExchangeDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/PaymentReceiverDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/dto/RemoveMoneyDto.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/Client.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/Credit.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/CreditRequest.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/PayedInterest.java
  client/src/main/java/rs/edu/raf/si/bank2/client/models/mongodb/Payment.java
  client/src/main/java/rs/edu/raf/si/bank2/client/repositories/mongodb/CreditRequestRepository.java
  client/src/main/java/rs/edu/raf/si/bank2/client/repositories/mongodb/PayedInterestRepository.java
  client/src/main/java/rs/edu/raf/si/bank2/client/repositories/mongodb/PaymentRepository.java
  client/src/main/java/rs/edu/raf/si/bank2/client/services/BalanceService.java
  client/src/main/java/rs/edu/raf/si/bank2/client/services/CreditService.java
  client/src/main/java/rs/edu/raf/si/bank2/client/services/PaymentService.java
  docker-compose.yml
  docker/client.Dockerfile
  docker/main.Dockerfile
  docker/otc.Dockerfile
  docker/users.Dockerfile
  main/pom.xml
  main/src/main/java/rs/edu/raf/si/bank2/main/configuration/RedisConfiguration.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/ExchangeService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/ForexService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/FutureService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/OptionService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/StockService.java
  main/src/test/java/rs/edu/raf/si/bank2/main/services/ExchangeServiceTest.java
  otc/pom.xml
  otc/src/main/java/rs/edu/raf/si/bank2/otc/configuration/RedisConfiguration.java
  users/pom.xml
  users/src/main/java/rs/edu/raf/si/bank2/users/configuration/RedisConfiguration.java
Labels: size/XXL

#294 Added Prometheus, Grafan support and monitoring
  client/pom.xml
  client/src/main/java/rs/edu/raf/si/bank2/client/configuration/MetricsConfig.java
  client/src/main/java/rs/edu/raf/si/bank2/client/configuration/SpringSecurityConfig.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/BalanceController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/ClientController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/CreditController.java
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/PaymentController.java
  client/src/main/resources/application.properties
  docker-compose.yml
  grafana/spring-dashboard.json
  main/pom.xml
  main/src/main/java/rs/edu/raf/si/bank2/main/configuration/MetricsConfig.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/BalanceController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/CurrencyController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/ExchangeController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/ForexController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/FutureController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/OptionController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/OrderController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/ReserveController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/StockController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/TransactionController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/UserController.java
  main/src/main/resources/application.properties
  otc/pom.xml
  otc/src/main/java/rs/edu/raf/si/bank2/otc/configuration/MetricsConfig.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/configuration/SpringSecurityConfig.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/BankAccountController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/CompanyController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/ContactPersonController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/MarginBalanceController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/MarginTransactionController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/OtcController.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/controllers/pdf/FileController.java
  otc/src/main/resources/application.properties
  prometheus.yml
  users/pom.xml
  users/src/main/java/rs/edu/raf/si/bank2/users/configuration/MetricsConfig.java
  users/src/main/java/rs/edu/raf/si/bank2/users/configuration/SpringSecurityConfig.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/AuthenticationController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/ServiceAuthController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/controllers/UserServiceController.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/AuthorisationService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/MailingService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/PermissionService.java
  users/src/main/java/rs/edu/raf/si/bank2/users/services/UserService.java
  users/src/main/resources/application.properties
  users/src/test/java/rs/edu/raf/si/bank2/users/cucumber/integration/auth/AuthIntegrationSteps.java
  users/src/test/java/rs/edu/raf/si/bank2/users/cucumber/integration/authFailures/AuthFailuresIntegrationSteps.java
  users/src/test/java/rs/edu/raf/si/bank2/users/cucumber/integration/serviceAuth/ServiceAuthIntegrationSteps.java
  users/src/test/java/rs/edu/raf/si/bank2/users/cucumber/integration/serviceAuthFailures/ServiceAuthFailuresIntegrationSteps.java
  users/src/test/java/rs/edu/raf/si/bank2/users/services/AuthorisationServiceTest.java
  users/src/test/java/rs/edu/raf/si/bank2/users/services/MailingServiceTest.java
Labels: lgtm, size/XXL, approved

#297 Added monitoring, formatting, snyk
  .idea/runConfigurations/Format_Client.xml
  .idea/runConfigurations/Run_Client__local_dev_.xml
  .idea/runConfigurations/Run_Client__local_test_.xml
  .idea/runConfigurations/Test_Client.xml
  .prow/branch-verify.yaml
  .prow/client.yaml
  .prow/main.yaml
  .prow/otc.yaml
  .prow/users.yaml
  client/src/main/java/rs/edu/raf/si/bank2/client/controllers/ClientController.java
Labels: size/L, approved

#298 testovi, otc bug fix, options safety insured
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/OptionController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/ReserveController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/repositories/mariadb/UserStocksRepository.java
  main/src/main/java/rs/edu/raf/si/bank2/main/utils/OptionDateScraper.java
  otc/src/main/java/rs/edu/raf/si/bank2/otc/repositories/mariadb/PasswordResetTokenRepository.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/cucumber/integration/auth/AuthIntegrationSteps.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/cucumber/integration/authFailures/AuthFailuresIntegrationSteps.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/cucumber/integration/otcFailures/OtcFailuresIntegrationSteps.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/cucumber/integration/otcFailures/OtcFailuresIntegrationTest.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/cucumber/integration/otcFailures/OtcFailuresIntegrationTestConfig.java
  otc/src/test/java/rs/edu/raf/si/bank2/otc/cucumber/integration/serviceAuth/ServiceAuthIntegrationSteps.java
  otc/src/test/resources/features/otc-integration/otc.feature
  otc/src/test/resources/features/otc-integration/otcFailure.feature
  users/src/main/java/rs/edu/raf/si/bank2/users/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XL

#299 Fix CSV loading in Main, add Docker run configs, update docker-compose profiles
  .idea/runConfigurations/docker_compose__core_.xml
  .idea/runConfigurations/docker_compose__except_client_.xml
  .idea/runConfigurations/docker_compose__except_main_.xml
  .idea/runConfigurations/docker_compose__except_otc_.xml
  .idea/runConfigurations/docker_compose__except_users_.xml
  .idea/runConfigurations/docker_compose__full_.xml
  .idea/runConfigurations/docker_compose__only_client_.xml
  .idea/runConfigurations/docker_compose__only_main_.xml
  .idea/runConfigurations/docker_compose__only_otc_.xml
  .idea/runConfigurations/docker_compose__only_users_.xml
  .idea/runConfigurations/docker_test_client.xml
  .idea/runConfigurations/docker_test_main.xml
  .idea/runConfigurations/docker_test_otc.xml
  .idea/runConfigurations/docker_test_users.xml
  docker-compose.yml
  docker/client.Dockerfile
  docker/main.Dockerfile
  docker/otc.Dockerfile
  docker/users.Dockerfile
  main/pom.xml
  main/src/main/java/rs/edu/raf/si/bank2/main/bootstrap/BootstrapData.java
  main/src/main/java/rs/edu/raf/si/bank2/main/bootstrap/readers/CSVReader.java
  main/src/main/java/rs/edu/raf/si/bank2/main/bootstrap/readers/CurrencyReader.java
  main/src/main/resources/csvs/exchange_0.csv
  main/src/main/resources/csvs/exchange_1.csv
  main/src/main/resources/csvs/stock_history.csv
  main/src/main/resources/csvs/stocks.csv
Labels: approved, size/XL

#300 testovi fixani all good
  main/src/main/java/rs/edu/raf/si/bank2/main/bootstrap/BootstrapData.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/users/UsersIntegrationSteps.java
  main/src/test/resources/features/user-integration/users.feature
  users/src/main/java/rs/edu/raf/si/bank2/users/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/M

#301 jos par testova
  client/src/main/java/rs/edu/raf/si/bank2/client/services/CreditService.java
  client/src/test/java/rs/edu/raf/si/bank2/client/cucumber/integration/credit/CreditIntegrationSteps.java
  client/src/test/resources/features/credit-integration/credit.feature
Labels: approved, size/M

#304 Sync sprint-6 with main and dev, minor fixes
  .prow/branch-verify.yaml
  client/src/test/java/rs/edu/raf/si/bank2/client/cucumber/integration/credit/CreditIntegrationSteps.java
  grafana/spring-dashboard.json
Labels: lgtm, size/XXL, approved

#316 Unit testovi za StockService
  main/src/main/java/rs/edu/raf/si/bank2/main/controllers/ExchangeController.java
  main/src/main/java/rs/edu/raf/si/bank2/main/dto/UserDto.java
  main/src/main/java/rs/edu/raf/si/bank2/main/exceptions/BalanceNotFoundException.java
  main/src/main/java/rs/edu/raf/si/bank2/main/exceptions/NotEnoughMoneyException.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/StockService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/UserService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/UserStockService.java
  main/src/main/java/rs/edu/raf/si/bank2/main/services/workerThreads/StockBuyWorker.java
  main/src/test/java/rs/edu/raf/si/bank2/main/cucumber/integration/exchangesFailure/ExchangeFailuresIntegrationSteps.java
  main/src/test/java/rs/edu/raf/si/bank2/main/services/DtoTest.java
  main/src/test/java/rs/edu/raf/si/bank2/main/services/StockServiceTest.java
  main/src/test/java/rs/edu/raf/si/bank2/main/services/UserServiceTest.java
  main/src/test/resources/features/exchange-integration/exchange.feature
  main/src/test/resources/features/exchange-integration/exchangeFailures.feature
  otc/src/test/java/rs/edu/raf/si/bank2/otc/cucumber/integration/contactPerson/ContactPersonIntegrationTestConfig.java
  otc/src/test/resources/features/bankAccount-integration/bankAccountFailure.feature
  otc/src/test/resources/features/company-integration/companyFailure.feature
Labels: size/XL

#318 Optimize CI jobs
  .prow/client.yaml
  .prow/main.yaml
  .prow/otc.yaml
  .prow/users.yaml
Labels: size/L, approved
