Repository RAF-SI-2022/Banka-2-Backend, pull requests merged in 2023-03, with the labels that each got.

#27 Inicijalizacija projekta: Spring Boot
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/raf/si/Banka2Backend/Banka2BackendApplication.java
  src/main/java/com/raf/si/Banka2Backend/ServletInitializer.java
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/configuration/SpringSecurityConfig.java
  src/main/java/com/raf/si/Banka2Backend/controllers/AuthetificationController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/dto/UserDto.java
  src/main/java/com/raf/si/Banka2Backend/filters/JwtFilter.java
  src/main/java/com/raf/si/Banka2Backend/models/User.java
  src/main/java/com/raf/si/Banka2Backend/repositories/UserRepository.java
  src/main/java/com/raf/si/Banka2Backend/requests/LoginRequest.java
  src/main/java/com/raf/si/Banka2Backend/requests/RegisterRequest.java
  src/main/java/com/raf/si/Banka2Backend/responses/LoginResponse.java
  src/main/java/com/raf/si/Banka2Backend/responses/RegisterResponse.java
  src/main/java/com/raf/si/Banka2Backend/services/AuthorisationService.java
  src/main/java/com/raf/si/Banka2Backend/services/UserService.java
  src/main/java/com/raf/si/Banka2Backend/utils/JwtUtil.java
  src/main/resources/application.properties
  src/test/java/com/raf/si/Banka2Backend/Banka2BackendApplicationTests.java
Labels: size/XL, needs-ok-to-test

#29 Sprint 1 - Database configuration
  myFlywayConfig.conf
  pom.xml
  src/main/java/com/raf/si/Banka2Backend/models/User.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/main/resources/db/migration/V1_0__Initial_migration_users_table.sql
Labels: size/M, needs-ok-to-test

#30 Feature - Permissions
  src/main/java/com/raf/si/Banka2Backend/models/Permission.java
  src/main/java/com/raf/si/Banka2Backend/models/User.java
  src/main/resources/db/migration/V1_1__Permission_support_added.sql
Labels: size/M, needs-ok-to-test

#34 Kontroleri, servisi, login, register
  src/main/java/com/raf/si/Banka2Backend/configuration/AppConfig.java
  src/main/java/com/raf/si/Banka2Backend/controllers/AuthetificationController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/models/User.java
  src/main/java/com/raf/si/Banka2Backend/repositories/UserRepository.java
  src/main/java/com/raf/si/Banka2Backend/requests/LoginRequest.java
  src/main/java/com/raf/si/Banka2Backend/requests/RegisterRequest.java
  src/main/java/com/raf/si/Banka2Backend/responses/LoginResponse.java
  src/main/java/com/raf/si/Banka2Backend/responses/RegisterResponse.java
  src/main/java/com/raf/si/Banka2Backend/services/UserService.java
  src/main/java/com/raf/si/Banka2Backend/services/UserServiceInteface.java
  src/main/java/com/raf/si/Banka2Backend/utils/JwtUtil.java
Labels: lgtm, size/L, needs-ok-to-test

#35 added authorisation, added migartion script
  pom.xml
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/filters/JwtFilter.java
  src/main/java/com/raf/si/Banka2Backend/models/Permission.java
  src/main/java/com/raf/si/Banka2Backend/models/PermissionName.java
  src/main/java/com/raf/si/Banka2Backend/models/User.java
  src/main/java/com/raf/si/Banka2Backend/repositories/PermissionRepository.java
  src/main/java/com/raf/si/Banka2Backend/repositories/UserRepository.java
  src/main/java/com/raf/si/Banka2Backend/requests/RegisterRequest.java
  src/main/java/com/raf/si/Banka2Backend/responses/RegisterResponse.java
  src/main/java/com/raf/si/Banka2Backend/services/AuthorisationService.java
  src/main/java/com/raf/si/Banka2Backend/services/UserService.java
  src/main/java/com/raf/si/Banka2Backend/utils/JwtUtil.java
  src/main/resources/db/migration/V1_2__Changed_column_names.sql
Labels: size/L

#36 Dodata validacija
  pom.xml
  src/main/java/com/raf/si/Banka2Backend/models/User.java
  src/test/java/com/raf/si/Banka2Backend/Banka2BackendUserServiceUnitTests.java
Labels: size/L

#37 updated UserController, add PermissionService
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/AuthetificationController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/repositories/PermissionRepository.java
  src/main/java/com/raf/si/Banka2Backend/requests/RegisterRequest.java
  src/main/java/com/raf/si/Banka2Backend/responses/RegisterResponse.java
  src/main/java/com/raf/si/Banka2Backend/services/PermissionService.java
  src/main/java/com/raf/si/Banka2Backend/services/PermissionServiceInterface.java
Labels: size/L

#39 Regex hotfix
  src/main/java/com/raf/si/Banka2Backend/models/User.java
Labels: size/S

#40 zakomentarisan regex usera, dodat find by email, dodat deactivate (tmp)
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/models/User.java
Labels: size/M

#42 Feature docker
  Dockerfile
  Makefile
  README.md
  docker-compose.yml
  make.bat
  myFlywayConfig.conf
  pom.xml
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
Labels: size/L

#43 Ponovo ukljucena validacija za email i jmbg
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/models/User.java
  src/test/java/com/raf/si/Banka2Backend/Banka2BackendUserServiceUnitTests.java
Labels: size/S

#46 Added baseline validation to flyway container config
  docker-compose.yml
  flywayConfig/myFlywayConfig.conf
  myFlywayConfig.conf
Labels: size/XS

#47 Fixed user regex patterns
  src/main/java/com/raf/si/Banka2Backend/models/User.java
Labels: size/S

#49 Dodate funkcije za update/register, permisije i jos
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/AuthetificationController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/models/Permission.java
  src/main/java/com/raf/si/Banka2Backend/models/User.java
  src/main/java/com/raf/si/Banka2Backend/repositories/PermissionRepository.java
  src/main/java/com/raf/si/Banka2Backend/requests/ChangePasswordRequest.java
  src/main/java/com/raf/si/Banka2Backend/requests/LoginRequest.java
  src/main/java/com/raf/si/Banka2Backend/requests/UpdateProfileRequest.java
  src/main/java/com/raf/si/Banka2Backend/requests/UpdateUserRequest.java
  src/main/java/com/raf/si/Banka2Backend/responses/LoginResponse.java
  src/main/java/com/raf/si/Banka2Backend/services/UserService.java
  src/main/java/com/raf/si/Banka2Backend/services/UserServiceInteface.java
Labels: size/L, priority/urgent

#50 mini fix oko isActive kad se updatuje
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
Labels: size/XS

#53 Sprint 1
  pom.xml
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/AuthenticationController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/AuthetificationController.java
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/dto/PasswordRecoveryDto.java
  src/main/java/com/raf/si/Banka2Backend/models/PasswordResetToken.java
  src/main/java/com/raf/si/Banka2Backend/models/Permission.java
  src/main/java/com/raf/si/Banka2Backend/models/User.java
  src/main/java/com/raf/si/Banka2Backend/repositories/PasswordResetTokenRepository.java
  src/main/java/com/raf/si/Banka2Backend/repositories/PermissionRepository.java
  src/main/java/com/raf/si/Banka2Backend/services/AuthorisationService.java
  src/main/java/com/raf/si/Banka2Backend/services/MailingService.java
  src/main/java/com/raf/si/Banka2Backend/services/PermissionService.java
  src/main/java/com/raf/si/Banka2Backend/services/UserService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/PermissionServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/UserServiceInterface.java
  src/main/resources/db/migration/V1_3__Password_reset.sql
Labels: size/L

#55 -Tests added
  src/test/java/com/raf/si/Banka2Backend/controllers/UserControllerTest.java
  src/test/java/com/raf/si/Banka2Backend/services/AutorisationServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/PermissionServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/UserServiceTest.java
Labels: size/L

#54 Hotfix za testove i user regex patterne
  src/main/java/com/raf/si/Banka2Backend/models/Permission.java
  src/main/java/com/raf/si/Banka2Backend/models/User.java
  src/test/java/com/raf/si/Banka2Backend/services/AutorisationServiceTest.java
Labels: priority/urgent, size/M

#67 Fix za port za lokalnu bazu
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/requests/RegisterRequest.java
  src/main/resources/application-local.properties
Labels: size/S

#68 Uklonjeni suvisni paketi i klase iz test dela aplikacije
  src/test/java/com/raf/si/Banka2Backend/contollers/UserControllerTest.java
  src/test/java/com/raf/si/Banka2Backend/controllers/UserControllerTest.java
  src/test/java/com/raf/si/Banka2Backend/services/AutorisationServiceTest.java
Labels: size/L

#70 Podesen docker radi (ubijen health_check za usless baze), dodati success testovi za user controller, i login funkciju
  README.md
  docker-compose.yml
  git/hooks/pre-push
  src/main/java/com/raf/si/Banka2Backend/controllers/UserController.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/UserNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/models/users/Permission.java
  src/main/java/com/raf/si/Banka2Backend/models/users/User.java
  src/main/java/com/raf/si/Banka2Backend/services/UserService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/UserServiceInterface.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/users/UsersIntegrationSteps.java
  src/test/resources/features/user-integration/users.feature
Labels: size/XL

#71 sredjeni unite i integracioni (success) testovi (37 passed) (1-will fail if no in docker)
  src/main/java/com/raf/si/Banka2Backend/exceptions/PasswordResetTokenNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/services/UserService.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/users/UsersIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/services/AuthorisationServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/PermissionServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/UserServiceTest.java
Labels: size/L

#81 exchange sa unit testovima i podacima u csvu
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/controllers/ExchangeController.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/ExchangeNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Exchange.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/ExchangeRepository.java
  src/main/java/com/raf/si/Banka2Backend/services/ExchangeService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/ExchangeServiceInterface.java
  src/main/resources/db/migration/V1_4__Exchange.sql
  src/main/resources/exchange.csv
  src/test/java/com/raf/si/Banka2Backend/services/ExchangeServiceTest.java
Labels: size/XL

#83 Currency Model
  pom.xml
  src/main/java/com/raf/si/Banka2Backend/bootstrap/BootstrapData.java
  src/main/java/com/raf/si/Banka2Backend/bootstrap/readers/CountryCodeMapper.java
  src/main/java/com/raf/si/Banka2Backend/bootstrap/readers/CurrencyCSV.java
  src/main/java/com/raf/si/Banka2Backend/bootstrap/readers/CurrencyReader.java
  src/main/java/com/raf/si/Banka2Backend/controllers/CurrencyController.java
  src/main/java/com/raf/si/Banka2Backend/dto/InflationDto.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/CurrencyNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/exceptions/ExchangeNotFoundException.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Currency.java
  src/main/java/com/raf/si/Banka2Backend/models/mariadb/Inflation.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/CurrencyRepository.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/ExchangeRepository.java
  src/main/java/com/raf/si/Banka2Backend/repositories/mariadb/InflationRepository.java
  src/main/java/com/raf/si/Banka2Backend/services/CurrencyService.java
  src/main/java/com/raf/si/Banka2Backend/services/ExchangeService.java
  src/main/java/com/raf/si/Banka2Backend/services/InflationService.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/CurrencyServiceInterface.java
  src/main/java/com/raf/si/Banka2Backend/services/interfaces/InflationServiceInterface.java
  src/main/resources/currencies/currencies.csv
  src/main/resources/currencies/inflations.csv
  src/main/resources/db/migration/V2_0__Initial_migration_currencies_table.sql
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/currencies/CurrenciesIntegrationSteps.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/currencies/CurrenciesIntegrationTest.java
  src/test/java/com/raf/si/Banka2Backend/cucumber/integration/currencies/CurrenciesIntegrationTestConfig.java
  src/test/java/com/raf/si/Banka2Backend/services/CurrencyServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/ExchangeServiceTest.java
  src/test/java/com/raf/si/Banka2Backend/services/InflationServiceTest.java
  src/test/resources/features.currency-integration/currencies.feature
Labels: size/XXL
